[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'vim-scripts/mru.vim'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'preservim/nerdcommenter'

[[plugins]]
repo = 'dracula/vim'
name = 'dracula'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'unblevable/quick-scope'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'bronson/vim-visual-star-search'
